version: "3.9"
networks:
  default:
    external:
      name: localdev
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    #image: blakeblackshear/frigate:0.8.4-aarch64
    image: blakeblackshear/frigate:0.8.4-aarch64
      # depends_on:
      #   - mosquitto
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb
    #  - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml:ro
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    expose: 
      - 5000
      - 1935
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "visi2Ion"
      MQTT_HOST: mosquitto