version: "3.9"
networks:
  default:
    external:
      name: localdev
services:
  # mosquitto:
  #   container_name: mosquitto
  #   image: eclipse-mosquitto:latest
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"
  #   expose:
  #     - "1883"
  #     - "9001"
  #   volumes:
  #     - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     - ./data-mosquitto/data:/mosquitto/data
  #     - ./data-mosquitto/log:/mosquitto/log
  #   environment:
  #     MQTT_HOST: mosquitto  
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    #image: blakeblackshear/frigate:0.8.4-aarch64
    image: blakeblackshear/frigate:0.8.4-amd64
      # depends_on:
      #   - mosquitto
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb
    #  - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml:ro
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "visi2Ion"
      MQTT_HOST: mosquitto